# Sidebar navigation

- label: 'نظرة عامة'
  link: '/overview'
- label: 'الصوت والنبرة'
  link: '/voice-and-tone'
- label: 'طُرق الكتابة الفعّالة'
  link: '/actionable-language'
- label: 'الأسلوب وآلية الكتابة'
  link: '/style-and-mechanics'
- label: 'قوائم الكلمات'
  link: '/word-list'
- label: 'المراجع والمصادر'
  link: '/references'

# Examples

#- label: 'Introduction'
#  link: '/'
#- label: 'Getting started'
#  link: '/getting-started'
#- label: Usage
#  items:
#    - label: 'Creating docs'
#      link: '/usage/creating-docs'
#    - label: 'Navigation'
#      link: '/usage/navigation'
#    - label: 'Customizing'
#      link: '/usage/customizing'
#    - label: 'Using YAML files'
#      link: '/usage/using-yaml-files'
#    - label: 'Remark Plugins'
#      link: '/usage/remark-plugins'
#- label: More
#  items:
#    - label: FAQ
#      link: /faq
#    - label: 'Github'
#      link: https://github.com/jpedroschmitz/rocketdocs
